### ISSUE TITLE
warning on non existing organization url

### ISSUE THREAD

**Issue by david-gang** [jekyll/github-metadata#83]
Hi all

I run bundle exec jekyll serve --verbose and i get in the trace:
   GitHub Metadata: Initializing...
   GitHub Metadata: Generating for david-gang/david-gang.github.io
   GitHub Metadata: Calling @client.pages("david-gang/david-gang.github.io", {})
   GitHub Metadata: Generating for david-gang/david-gang.github.io
   GitHub Metadata: Calling @client.pages("david-gang/david-gang.github.io", {})
   GitHub Metadata: Calling @client.contributors("david-gang/david-gang.github.io")
   GitHub Metadata: Calling @client.contributors("david-gang/david-gang.github.io")
   GitHub Metadata: Calling @client.repository("david-gang/david-gang.github.io")
   GitHub Metadata: Calling @client.repository("david-gang/david-gang.github.io")
   GitHub Metadata: Calling @client.organization("david-gang")
   GitHub Metadata: GET https://api.github.com/orgs/david-gang: 404 - Not Found // See: https://developer.github.com/v3
   GitHub Metadata: Calling @client.organization("david-gang")
   GitHub Metadata: GET https://api.github.com/orgs/david-gang: 404 - Not Found // See: https://developer.github.com/v3
   GitHub Metadata: Calling @client.list_repos("david-gang", {"type"=>"public"})
   GitHub Metadata: Calling @client.list_repos("david-gang", {"type"=>"public"})
   GitHub Metadata: Calling @client.releases("david-gang/david-gang.github.io")
   GitHub Metadata: Calling @client.releases("david-gang/david-gang.github.io")

I don't understand why it tries to acess: 
https://api.github.com/orgs/david-gang
It should be
https://api.github.com/users/david-gang

If this is ok that the organization page does not exist it should not write an error message.
Is this a misconfiguration on my side or a defect

I asked this question in jekyll talk but no one answered me
https://talk.jekyllrb.com/t/github-metadata-not-found-it-think-that-i-am-an-organization/3417

 so i assume it is a defect
Thanks,
David

**Comment by TheBigLaskowski** [comment]
I too have experienced this exact issue for several weeks now, really hoping jekyll-github-metadata will be updated to use the /users/ directory instead of the /orgs/ URL to clear this error / warning message

**Comment by maban** [comment]
Aghh, this! I couldn't work out why I was getting this error all the time. I'm using Jekyll and GitHub Pages, and get this error on my open source repo every time I try and build. Tried so many different authentication methods and none of them work.

**Comment by latsa** [comment]
Same issue here. This is not an authentication issue, as described in [GitHub API errors #374.](https://github.com/github/pages-gem/issues/374) The wrong URL is used for accounts not having type: "Organization". The URL [https://api.github.com/orgs/david-gang](https://api.github.com/orgs/david-gang) should read [https://api.github.com/userss/david-gang](https://api.github.com/users/david-gang)

**Comment by parkr** [comment]
Fixed by #86, I believe.

**Comment by ebagdasa** [comment]
I don't get it, as it is the API issue not the #86 which is just log problem,

**Comment by parkr** [comment]
@ebagdasa We ask GitHub if the user account the repository belongs to is a `User` or `Organization`. We do that by calling `client.organization("username")` and seeing if it returns something. If it does, then it's an `Organization`. If it doesn't then it's a `User`. The reason it's a log issue is because getting a 404 is expected when the username is a `User`. We were logging it which looked scary, but it wasn't necessary to log it.

**Comment by tbarron** [comment]
This is still broken for users who are associated with an organization. I think client.organization("tbarron") will return something because I'm associated with an organization for work, which means that my personal pages will be treated as orgs when they should be users.
